### ISSUE TITLE
Testing clarity

### ISSUE THREAD

**Issue by DSFrey** [catdude2000/data-structures-and-algorithms#37]
Please either write this function
https://github.com/catdude2000/data-structures-and-algorithms/blob/4bd9459c09900adb2ef627f65ee91d29e37013d6/javascript/code-challenges/challenges-15.test.js#L100-L102
or skip this test (`xdescribe`)
https://github.com/catdude2000/data-structures-and-algorithms/blob/4bd9459c09900adb2ef627f65ee91d29e37013d6/javascript/code-challenges/challenges-15.test.js#L204-L209
so that it is easier to see if the tests for your new code challenges are passing or not.

**Comment by catdude2000** [comment]
In linked list insertions pr
